OnlineShop/OnlineShop/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Domain.Models.Identity;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = Role.administrator)]
    public class HomeController : Controller
    {
        public IActionResult Index() => View();
    }
}

OnlineShop/OnlineShop/Components/BrandsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Services.Interfaces;
using OnlineShop.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Components
{
    public class BrandsViewComponent : ViewComponent
    {
        private readonly IProductService productService;
        public BrandsViewComponent(IProductService productService)
        {
            this.productService = productService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var brands = await GetBrands();
            return View(brands);
        }
        private Task<List<BrandViewModel>> GetBrands()
        {
            var task = Task.Run(() => 
            {
                var brands = productService.GetBrands();
                return brands.Select(b => new BrandViewModel
                {
                    Id = b.Id,
                    Name = b.Name,
                    Order = b.Order,
                    ProductsCount = 0
                }).OrderBy(b => b.Order).ToList();
            });
            return task;
        }
    }
}

OnlineShop/OnlineShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineShop.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index() => View();
    }
}

OnlineShop/OnlineShop/Views/Home/Employess.cshtml
@model IEnumerable<OnlineShop.Models.Employee>
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Сотрудники</title>
</head>
<body>
	<h3>Сотрудники</h3>
	<table>
		<thead>
			<tr>
				<th>#</th>
				<th>Фамилия</th>
				<th>Имя</th>
				<th>Отчество</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td>
						<a href="~/Home/SelectedEmployee/+@item.Id">@item.Id</a>
					</td>
					<td>@item.FirstName</td>
					<td>@item.SurName</td>
					<td>@item.Patronymic</td>
				</tr>
			}
		</tbody>
	</table>
</body>
</html>

OnlineShop/OnlineShop/Views/Home/Index.cshtml
<section id="slider">
	<partial name="Partial/_Slider" />
</section>

<section>
	<div class="container">
		<div class="row">
			<div class="col-sm-3">
				<div class="left-sidebar">
					<vc:category />
					@*<partial name="Partial/_Category" />*@
					<vc:brands />
					@*<partial name="Partial/_Brands" />*@
					<partial name="Partial/_Price" />
					<div class="shipping text-center">
						<!--shipping-->
						<img src="~/images/home/shipping.jpg" alt="" />
					</div><!--/shipping-->
				</div>
			</div>

			<div class="col-sm-9 padding-right">
				<vc:initial-products />
				@*<partial name="Partial/_Features" model="products"/>*@
				<partial name="Partial/_Tabs" />
				<partial name="Partial/_Recommended" />
			</div>
		</div>
	</div>
</section>

OnlineShop/OnlineShop/Views/Home/SelectedEmployee.cshtml
@model OnlineShop.Models.Employee
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Карта сотрудника</title>
</head>
<body>
	<h3>Карта сотрудника</h3>
	<table>
		<thead>
			<tr>
				<th>#</th>
				<th>Фамилия</th>
				<th>Имя</th>
				<th>Отчество</th>
				<th>Возраст</th>
				<th>Адрес</th>
				<th>Email</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>@Model.Id</td>
				<td>@Model.FirstName</td>
				<td>@Model.SurName</td>
				<td>@Model.Patronymic</td>
				<td>@Model.Age</td>
				<td>@Model.Address</td>
				<td>@Model.Email</td>
			</tr>
		</tbody>
	</table>
	<hr/>
	<a href = "~/">К списку сотрудников</a>
</body>
</html>